CREATE TABLE [dbo].[UserRoles] (
    [Id] INT NOT NULL,
    [Name] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UIX_UserRoles_Name] UNIQUE NONCLUSTERED ([Name] ASC)
);